### PR TITLE
Allow playbook files names to vary

### PR DESCRIPTION
**Pull request by rthallisey**
Instead of requiring playbooks with the names of each ACTION, allow
for a single playbook using the name of the apb and pass in the variable
action.

### CODE REVIEW

**Comment by djzager** [comment]
I don't think we should be using the `action` variable name since I have been seeing this in the logs of APB runs:

```
[WARNING]: Found variable using reserved name: action
```

We should probably sync this up with our Service Bundle discussion and come up with something descriptive and generic.

**Comment by rthallisey** [comment]
Didn't know that about the action var.  We'll have to change the name.

**Comment by jmrodri** [comment]
What prompted this? What's the longer term strategy here? The initial mapping of the actions mapped to the OSB spec.  I'm not against making things more flexible, but I'd like to know what's driving this. There is something to be said for being opinionated in a specification.

**Comment by jmrodri** [comment]
What actions are allowed? What does it mean to have a foobar action? Part of me feels this is something that should have been a proposal to discuss what we're trying to solve by doing this. Maybe I'm missing something.

**Comment by rthallisey** [comment]
> What prompted this? What's the longer term strategy here? The initial mapping of the actions mapped to the OSB spec. I'm not against making things more flexible, but I'd like to know what's driving this. There is something to be said for being opinionated in a specification.
>
The biggest driver is for folks to take existing ansible playbooks and allow them to easily convert them to APBs.  In the kubevirt-ansible directory, I think there is going to be multiple APBs.  In order to maintain the structure of the repo, I would like to have playbooks have the names of their components and then deal with the actions at a lower level.

**Comment by rthallisey** [comment]
closing until proposal is merged: https://github.com/openshift/ansible-service-broker/pull/815

**Pull request closed without merging**
